### ISSUE TITLE
Error in "select" function

### ISSUE THREAD

**Issue by LesleyAtwood** [Science-for-Nature-and-People/BibScan#15]
* I also had issues with the dependency packages not loading properly.

After manually loading the dependency packages, the following error appeared:

Error in select(., citation_title, citation_authors, citation_journal_name) : 
  could not find function "select"

___________________________________
Output prior to error:
Converting your isi collection into a bibliographic dataframe

Articles extracted   47 
Done!

Genereting affiliation field tag AU_UN from C1:  Done!

Parsed with column specification:
cols(
  study_id = col_integer(),
  deduplication_status = col_character(),
  citation_screening_status = col_character(),
  fulltext_screening_status = col_character(),
  data_extraction_screening_status = col_character(),
  data_source_type = col_character(),
  data_source_name = col_character(),
  data_source_url = col_character(),
  citation_title = col_character(),
  citation_abstract = col_character(),
  citation_authors = col_character(),
  citation_journal_name = col_character(),
  citation_journal_volume = col_integer(),
  citation_pub_year = col_integer(),
  citation_keywords = col_character(),
  fulltext_filename = col_character(),
  fulltext_exclude_reasons = col_character()
)

**Comment by brunj7** [comment]
this has been fixed
