### ISSUE TITLE
Other package dependencies

### ISSUE THREAD

**Issue by kanedan29** [Science-for-Nature-and-People/BibScan#2]
It looks like there are three more package dependencies when loading 'BibScan' - _rvest_, _jsonlite_, and _xml2_. I was getting error messages of 'function not found' for a few functions that I think are from those packages - "html_nodes" and "fromJSON" most notably.

**Comment by brunj7** [comment]
I pushed a new version of the package that should fix this. Please give it a try and let me know! You'll need to get a token to be able to use this version, please refer to the [README.md](https://github.com/Science-for-Nature-and-People/BibScan/blob/master/README.md)

**Comment by swood-ecology** [comment]
It seems like this has been resolved?
